var myarray =[
  {
    icon:'el-icon-s-tools',
    title:'管理系统',
    children:[
      {
        path:'/department',
        title:'部门管理'
      },
      {
        path:'/employee',
        title:'员工管理'
      },
      {
        path:'/jurisdiction',
        title:'权限管理'
      },
      {
        path:'/role',
        title:'角色管理'
      },
    ]
  },
  {
    icon:'el-icon-s-management',
    title:'数据管理',
    children:[
      {
        path:'/dictionaryMulu',
        title:'字典目录'
      },
      {
        path:'/dictionaryMingxi',
        title:'字典明细'
      },
    ]
  },
  {
    icon:'el-icon-service',
    title:'客户管理',
    children:[
      {
        path:'/customerOne',
        title:'客户列表'
      },
      {
        path:'/customerTwo',
        title:'潜在客户'
      },
      {
        path:'/customerThree',
        title:'客户池'
      },
      {
        path:'/customerFour',
        title:'失败客户'
      },
      {
        path:'/customerFive',
        title:'正式客户'
      },
      {
        path:'/customerSix',
        title:'流失客户'
      },
    ]
  },
  {
    icon:'el-icon-user-solid',
    title:'客户历史',
    children:[
      {
        path:'/historymove',
        title:'跟进历史'
      },
      {
        path:'/historygo',
        title:'移交历史'
      },
    ]
  },
  {
    icon:'el-icon-s-data',
    title:'报表统计',
    children:[
      {
        path:'/statistical',
        title:'潜在客户报表'
      },
    ]
  },
]

export default myarray
